// <auto-generated />
using System;
using GPFormula1.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPFormula1.Infra.Migrations
{
    [DbContext(typeof(F1DbContext))]
    [Migration("20260326043107_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipe", (string)null);
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.GrandePremio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Circuito")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TemporadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemporadaId");

                    b.ToTable("GrandePremio", (string)null);
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.ToTable("Piloto", (string)null);
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.ResultadoCorrida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GPId")
                        .HasColumnType("int");

                    b.Property<int>("PilotoId")
                        .HasColumnType("int");

                    b.Property<int?>("Posicao")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tempo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Voltas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GPId");

                    b.HasIndex("PilotoId");

                    b.ToTable("ResultadoCorrida", (string)null);
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.Temporada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int?>("CampeaoConstrutoresId")
                        .HasColumnType("int");

                    b.Property<int?>("CampeaoPilotosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampeaoConstrutoresId");

                    b.HasIndex("CampeaoPilotosId");

                    b.ToTable("Temporada", (string)null);
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.GrandePremio", b =>
                {
                    b.HasOne("GPFormula1.Dominio.Entidades.Temporada", "Temporada")
                        .WithMany("GPs")
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.Piloto", b =>
                {
                    b.HasOne("GPFormula1.Dominio.Entidades.Equipe", "Equipe")
                        .WithMany("Pilotos")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.ResultadoCorrida", b =>
                {
                    b.HasOne("GPFormula1.Dominio.Entidades.GrandePremio", "GP")
                        .WithMany("Resultados")
                        .HasForeignKey("GPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPFormula1.Dominio.Entidades.Piloto", "Piloto")
                        .WithMany()
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GP");

                    b.Navigation("Piloto");
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.Temporada", b =>
                {
                    b.HasOne("GPFormula1.Dominio.Entidades.Equipe", "CampeaoConstrutora")
                        .WithMany()
                        .HasForeignKey("CampeaoConstrutoresId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GPFormula1.Dominio.Entidades.Piloto", "CampeaoPiloto")
                        .WithMany()
                        .HasForeignKey("CampeaoPilotosId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CampeaoConstrutora");

                    b.Navigation("CampeaoPiloto");
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.Equipe", b =>
                {
                    b.Navigation("Pilotos");
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.GrandePremio", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.Temporada", b =>
                {
                    b.Navigation("GPs");
                });
#pragma warning restore 612, 618
        }
    }
}
