// <auto-generated />
using System;
using GPFormula1.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPFormula1.Infra.Migrations
{
    [DbContext(typeof(F1DbContext))]
    [Migration("20260330025704_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Red Bull Racing",
                            Pais = "Áustria"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Ferrari",
                            Pais = "Itália"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Mercedes",
                            Pais = "Alemanha"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "McLaren",
                            Pais = "Reino Unido"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Aston Martin",
                            Pais = "Reino Unido"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Alpine",
                            Pais = "França"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Williams",
                            Pais = "Reino Unido"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "RB",
                            Pais = "Itália"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Kick Sauber",
                            Pais = "Suíça"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Haas",
                            Pais = "Estados Unidos"
                        });
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.GrandePremio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Circuito")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TemporadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemporadaId");

                    b.ToTable("GrandePremio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Circuito = "Autódromo José Carlos Pace (Interlagos)",
                            Data = new DateTime(2024, 11, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Local = "São Paulo",
                            Nome = "GP do Brasil",
                            TemporadaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Circuito = "Circuit de Monaco",
                            Data = new DateTime(2024, 5, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Local = "Monte Carlo",
                            Nome = "GP de Mônaco",
                            TemporadaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Circuito = "Autodromo Nazionale di Monza",
                            Data = new DateTime(2024, 9, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Local = "Monza",
                            Nome = "GP da Itália",
                            TemporadaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Circuito = "Silverstone Circuit",
                            Data = new DateTime(2024, 7, 7, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Local = "Silverstone",
                            Nome = "GP da Inglaterra",
                            TemporadaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Circuito = "Circuit de Spa-Francorchamps",
                            Data = new DateTime(2024, 7, 28, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Local = "Spa-Francorchamps",
                            Nome = "GP da Bélgica",
                            TemporadaId = 1
                        });
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.ToTable("Piloto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipeId = 1,
                            Nacionalidade = "Holanda",
                            Nome = "Max Verstappen",
                            Numero = 1
                        },
                        new
                        {
                            Id = 2,
                            EquipeId = 1,
                            Nacionalidade = "México",
                            Nome = "Sergio Perez",
                            Numero = 11
                        },
                        new
                        {
                            Id = 3,
                            EquipeId = 2,
                            Nacionalidade = "Mônaco",
                            Nome = "Charles Leclerc",
                            Numero = 16
                        },
                        new
                        {
                            Id = 4,
                            EquipeId = 2,
                            Nacionalidade = "Espanha",
                            Nome = "Carlos Sainz",
                            Numero = 55
                        },
                        new
                        {
                            Id = 5,
                            EquipeId = 3,
                            Nacionalidade = "Reino Unido",
                            Nome = "Lewis Hamilton",
                            Numero = 44
                        },
                        new
                        {
                            Id = 6,
                            EquipeId = 3,
                            Nacionalidade = "Reino Unido",
                            Nome = "George Russell",
                            Numero = 63
                        },
                        new
                        {
                            Id = 7,
                            EquipeId = 4,
                            Nacionalidade = "Reino Unido",
                            Nome = "Lando Norris",
                            Numero = 4
                        },
                        new
                        {
                            Id = 8,
                            EquipeId = 4,
                            Nacionalidade = "Austrália",
                            Nome = "Oscar Piastri",
                            Numero = 81
                        },
                        new
                        {
                            Id = 9,
                            EquipeId = 5,
                            Nacionalidade = "Espanha",
                            Nome = "Fernando Alonso",
                            Numero = 14
                        },
                        new
                        {
                            Id = 10,
                            EquipeId = 5,
                            Nacionalidade = "Canadá",
                            Nome = "Lance Stroll",
                            Numero = 18
                        },
                        new
                        {
                            Id = 11,
                            EquipeId = 6,
                            Nacionalidade = "França",
                            Nome = "Pierre Gasly",
                            Numero = 10
                        },
                        new
                        {
                            Id = 12,
                            EquipeId = 6,
                            Nacionalidade = "França",
                            Nome = "Esteban Ocon",
                            Numero = 31
                        },
                        new
                        {
                            Id = 13,
                            EquipeId = 7,
                            Nacionalidade = "Tailândia",
                            Nome = "Alexander Albon",
                            Numero = 23
                        },
                        new
                        {
                            Id = 14,
                            EquipeId = 7,
                            Nacionalidade = "Estados Unidos",
                            Nome = "Logan Sargeant",
                            Numero = 2
                        },
                        new
                        {
                            Id = 15,
                            EquipeId = 8,
                            Nacionalidade = "Japão",
                            Nome = "Yuki Tsunoda",
                            Numero = 22
                        },
                        new
                        {
                            Id = 16,
                            EquipeId = 8,
                            Nacionalidade = "Austrália",
                            Nome = "Daniel Ricciardo",
                            Numero = 3
                        },
                        new
                        {
                            Id = 17,
                            EquipeId = 9,
                            Nacionalidade = "Finlândia",
                            Nome = "Valtteri Bottas",
                            Numero = 77
                        },
                        new
                        {
                            Id = 18,
                            EquipeId = 9,
                            Nacionalidade = "China",
                            Nome = "Zhou Guanyu",
                            Numero = 24
                        },
                        new
                        {
                            Id = 19,
                            EquipeId = 10,
                            Nacionalidade = "Dinamarca",
                            Nome = "Kevin Magnussen",
                            Numero = 20
                        },
                        new
                        {
                            Id = 20,
                            EquipeId = 10,
                            Nacionalidade = "Alemanha",
                            Nome = "Nico Hulkenberg",
                            Numero = 27
                        });
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.ResultadoCorrida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GPId")
                        .HasColumnType("int");

                    b.Property<int>("PilotoId")
                        .HasColumnType("int");

                    b.Property<int?>("Posicao")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tempo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Voltas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GPId");

                    b.HasIndex("PilotoId");

                    b.ToTable("ResultadoCorrida", (string)null);
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.Temporada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int?>("CampeaoConstrutoresId")
                        .HasColumnType("int");

                    b.Property<int?>("CampeaoPilotosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampeaoConstrutoresId");

                    b.HasIndex("CampeaoPilotosId");

                    b.ToTable("Temporada", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2024
                        });
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.GrandePremio", b =>
                {
                    b.HasOne("GPFormula1.Dominio.Entidades.Temporada", "Temporada")
                        .WithMany("GPs")
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.Piloto", b =>
                {
                    b.HasOne("GPFormula1.Dominio.Entidades.Equipe", "Equipe")
                        .WithMany("Pilotos")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.ResultadoCorrida", b =>
                {
                    b.HasOne("GPFormula1.Dominio.Entidades.GrandePremio", "GP")
                        .WithMany("Resultados")
                        .HasForeignKey("GPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPFormula1.Dominio.Entidades.Piloto", "Piloto")
                        .WithMany()
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GP");

                    b.Navigation("Piloto");
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.Temporada", b =>
                {
                    b.HasOne("GPFormula1.Dominio.Entidades.Equipe", "CampeaoConstrutora")
                        .WithMany()
                        .HasForeignKey("CampeaoConstrutoresId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GPFormula1.Dominio.Entidades.Piloto", "CampeaoPiloto")
                        .WithMany()
                        .HasForeignKey("CampeaoPilotosId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CampeaoConstrutora");

                    b.Navigation("CampeaoPiloto");
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.Equipe", b =>
                {
                    b.Navigation("Pilotos");
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.GrandePremio", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("GPFormula1.Dominio.Entidades.Temporada", b =>
                {
                    b.Navigation("GPs");
                });
#pragma warning restore 612, 618
        }
    }
}
